from .SDXLHSWQQuantizer import NODE_CLASS_MAPPINGS as QUANT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QUANT_DISPLAY
from .SDXLQuantStatsCollector import NODE_CLASS_MAPPINGS as CALIB_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CALIB_DISPLAY

NODE_CLASS_MAPPINGS = {**QUANT_MAPPINGS, **CALIB_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**QUANT_DISPLAY, **CALIB_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']